server:
  port: 30000
spring:
  application:
    name: rabbitmq-in-action
  rabbitmq:
    addresses: 192.168.136.133
    username: janwee
    password: janwee
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      bindings:
        inputText:
          destination: text
          group: ${spring.application.name}
        inputPerson:
          destination: person
          producer:
            deadLetterQueueName: personDLQ
          group: ${spring.application.name}
        outputText:
          destination: text
        outputPerson:
          destination: person